language: node_js
node_js: '10'
before_script:
script:
  - cd ./website
  - npm install
  - npm run build
deploy:
  on:
    branch: develop
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: staging.docket.fyi
  region: us-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: build
notifications:
  slack:
    secure: SXpymZ+IRYgzYerhTKC3y0Yj7a56AUs7naZZtJEsbsdHBj+IDV+SkzsMGv+KPB06qWzjfhCtCes+M46x4jlRO4jWeUQFK2cF6e84nGDGvtSL2olVMB2XkjpLVyMBQHj40/RwdySt0gSXDaTV6FE3wYysya/YnKyuM1U+ZT5gT2HIY7gC6hggGXNKIQpv5L9tRKLM7NzxKke6Ye9aCB/S3U1n/Xox8RYwCtccWjbmuCra4ojnPci9S1x3AMd83OnNiB+O5QU1Bv5MWbv4P07TAdJAWPJ/EOyXzZBeoIOU8xYV3+9ZI/WmEr7ivJyWFof9aoQZrDJC+V/zRwZH4Vyvd8sNr8U//eHjaf8bp/0zBD+pG9aU3WRJ6//mEOisFyQND/QyjxlPKjERoYZ5KI91ixX3/NV9bQygqxp4tNYH/kZnCO8LT6CLY5jRiwcQo5Y9i1/G2ppEHD56Xlov4c9ANFYQTb7/pKGm97nhsQMmh2df2RVGvEPsLZWqgAFJRsbsu191ZdOZ7o5ypfcv3xw0K4fnGIAVUaH6ZUVaDy8yqXZO24sdGkb59rySlzAsFp7OFL+4IpYUKQ5y2s/AOs6l4b8tsI75g3yL9W7r+kz7ropwIrifDLNDj9LgPtFeycQqICUy4rpTKJQ2ULW550MCuPjzBAqN+rLtYfJo9YpQn2o=
